services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  weaviate:
    image: semitechnologies/weaviate:1.25.1
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
    volumes:
      - weaviate_data:/var/lib/weaviate

  frontend:
    platform: linux/arm64
    build:
      context: ./
    container_name: weaviate-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - weaviate_frontend:/app/
      - /app/node_modules
      - /app/.next
    environment:
      #  - "host.docker.internal:host-gateway"
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
volumes:
  weaviate_data:
  weaviate_frontend:
  pgdata:
